### Calificaciones API
### 5B "5f5d6f09ae6e6a20d71c9a4d"


POST http://localhost:8626/reportes/create
content-type: application/json

{
    "curso": "5B",
    "_id":"5f6a88d14be55b0017d90533",
    "titular": "lizandro23difo@gmail.com",
    "periodo": "2020-2021"
    
}



### PF


GET http://localhost:8626/reporte/pdf/5f5d6f09ae6e6a20d71c9a4d


### Get reportes


GET http://localhost:8626/reportes/boletin/3B:2020-2021: HTTP/1.1
content-type: application/json




