### Calificaciones API

POST http://localhost:8626/reportes/create
content-type: application/json

{

    "curso": "5B",
    "titular": "lizandro23difo@gmail.com",
    "periodo": "2021-2022",
    "estado": true
}






